### ISSUE TITLE
Accessing the contest questions

### ISSUE THREAD

**Issue by kaushik-rishi** [Gradient-IIITS/CP-Solutions#1]
- I don't know whether opening an issue to ask this is valid or not

**By any chance can i access the contest questions on the Codeforces website or can you upload them to the repository.**

P.S : I have not attended the contest

**Comment by kaushik-rishi** [comment]
Feel free to inform in the comments before closing the issue if this is an invalid issue.

**Comment by ram-nad** [comment]
We will try to open question in the public.
